### ISSUE TITLE
mvSuSiE bubble plot add an option to show conditional effect

### ISSUE THREAD

**Issue by gaow** [stephenslab/mvsusieR#43]
Discussed this offline and @pcarbo has a draft implementation with demo. We can formally incorporate it. @stephens999 suggest using the conditional version as default.

- [x] Also change the figures from the manuscript into the conditional versions

**Comment by pcarbo** [comment]
@gaow Yes this is already implemented in `mvsusie_plot` the master branch. 
This really isn't an option—the conditional effects will always be shown (so long as `plot_z = FALSE`).

**Comment by pcarbo** [comment]
@gaow @zouyuxin I'm thinking it would be relatively easy to add the option of plotting only certain CSs using `cs_only`. When `cs_only` is a vector of numbers then only these CSs are shown. What do you think?

**Comment by stephens999** [comment]
related to this, my suggested default is to only show bubbles with lfsr<0.01 (rather than 0.05) and not bother with the shading levels which are pretty hard to distinguish anyway.

**Comment by pcarbo** [comment]
@stephens999 I've updated the `mvsusie_plot_simple` function as you suggested and updated the plot in the [tutorial](https://stephenslab.github.io/mvsusieR/articles/mvsusie_intro.html).

**Comment by zouyuxin** [comment]
In `mvsusie_plot`, I changed the default lfsr threshold to 0.01, and added an option to plot certain CSs. We have 2 functions for visualizing results, `mvsusie_plot` and `mvsusie_plot_simple`. `mvsusie_plot` is similar to the effect_plot in `mvsusie_plot_simple`, but includes all variants in the CSs, not just the sentinel variants. Shall we merge some of their functionalities to have one plot function?

**Comment by pcarbo** [comment]
@zouyuxin Yes, that would be nice. I'll leave this issue open as a reminder to do that. If you would like to give it a try, please go ahead.

**Comment by zouyuxin** [comment]
@pcarbo I added mvsusie_plot.R file with the combined plot function, `mvsusie_plot_test`. It's very similar to your `mvsusie_plot_simple`, but has options to plot all variants in the CSs, plot specific CSs, plot the conditional effect (default), and plot the original z scores. Could you take a look?

**Comment by pcarbo** [comment]
Thanks @zouyuxin, I think you called it `mvsusie_plot_combine`?

**Comment by zouyuxin** [comment]
you're right, I changed it last minute.

**Comment by pcarbo** [comment]
@zouyuxin I renamed `mvsusie_plot_combine` as `mvsusie_plot` and got rid of the old plotting functions, and I fixed a few things. See [here](https://stephenslab.github.io/mvsusieR/articles/mvsusie_intro.html) for an example of it working.

If everything looks okay to you, I think we can close this ticket. (I think we addressed all the suggestions that were made in the above comments.)

**Comment by zouyuxin** [comment]
Thanks Peter, it looks nice!
