### ISSUE TITLE
Trait-specific sample sizes?

### ISSUE THREAD

**Issue by harryyiheyang** [stephenslab/mvsusieR#52]
Hi there,
When I used the mvsusie_rss(), a universal sample size was required for all traits. However, this rarely happens in practice, e.g., the following numbers are the sample sizes of GWAS summary data:
      BMI       DBP       HDL       LDL       SBP       SMK       T2D        TG 
 747649.9  969641.0 1232760.0 1222125.6  946218.1  801386.2  747649.9 1242643.5 
Is it available to allow trait-specific sample sizes?
Thank you very much
Yihe

**Comment by gaow** [comment]
@zouyuxin do we take a vector of sample sizes ordered same way as the phenotypes?

**Comment by stephens999** [comment]
It's strongly advised to use the same individuals for all traits, using
imputation where necessary to achieve this. When you use different
individuals the results may be unreliable.

**Comment by harryyiheyang** [comment]
Hi @stephens999 and @gaow 
I appreciate your clarification! 
Yihe
